@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

### Get all Users
GET http://{{host}}/students

###
POST  http://{{host}}/students
Content-Type: {{contentType}}

{
    "name": "Mia Wallace",
    "email": "mia@pulp.com",
    "department": {
      "name": "Biology",
      "location": "Ed. 17 Viale delle Scienze, Palermo"
    },
    "subjects": [
      {
        "name": "Python",
        "mark": 100
      },
      {
        "name": "Typescript",
        "mark": 70
      },
      {
        "name": "Javascript",
        "mark": 75
      }
    ]
}

###
GET  http://{{host}}/students/6366a3c383979d4888d9f12c

###
PUT  http://{{host}}/students
Content-Type: {{contentType}}

{
    "id": "636523412a0965485c1b6173",
    "name": "Jules Winnifield",
    "email": "jules@pulp.com",
    "department": {
      "name": "Computer Science",
      "location": "Ed. 17 Viale delle Scienze, Palermo"
    },
    "subjects": [
      {
        "name": "Java",
        "mark": 100
      },
      {
        "name": "Python",
        "mark": 70
      },
      {
        "name": "Typescript",
        "mark": 75
      }
    ]
}

###
DELETE  http://{{host}}/students/63652dfa2a0965485c1b6176

###
GET  http://{{host}}/students/byname?name=Vincent%20Vega
###
GET  http://{{host}}/students/bynameandemail?name=Vincent%20Vega&email=vincent@pulp.com
###
GET  http://{{host}}/students/bynameoremail?name=Vincent%20Vega&email=mia@pulp.com


###
GET  http://{{host}}/students/withpagination?pageNo=2&pageSize=3
###
GET  http://{{host}}/students/withsorting


###
GET  http://{{host}}/students/bydepartmentid?deptId=6366a3bb83979d4888d9f128
###
GET  http://{{host}}/students/bysubjectid?subId=6366a81283979d4888d9f134

###
GET  http://{{host}}/students/byEmailLike?email=gmail
###
GET  http://{{host}}/students/byNameStartsWith?name=Vin