spring:
  profiles:
    active:
      - EN

server:
  port: 8080
  servlet:
    context-path: /

demo:
  message: "This is a message"
  version: 66
  javaHome: ${JAVA_HOME}

demo-props:
  pageSize: 10
  contact:
    pageSize: 5
    successMsg: The success message.
  branches:
    - NewYork
    - Delhi
    - Paris
    - Singapore
