#debug: true
#trace: true
logging:
  level:
    root:
      INFO
    dev:
      frizio:
        demo:
          controllers:
            DEBUG
          services:
            TRACE

server:
  port: 8080
  servlet:
    context-path: /

spring:
  profiles:
    active:
      - EN
      - local
  output:
    ansi:
      enabled: detect
      
# Note: Active profiles can be overridden with env variable SPRING_PROFILES_ACTIVE
# or using Java System Property "-D spring-boot.run.profiles"

# Configuration Properties
#demo:
#  message: "This is a message"
#  version: 66
#  javaHome: ${JAVA_HOME}
#
#demo-props:
#  pageSize: 10
#  contact:
#    pageSize: 5
#    successMsg: The success message.
#  branches:
#    - NewYork
#    - Delhi
#    - Paris
#    - Singapore

