spring:
  profiles:
    active:
      - EN

server:
  port: 8080
  servlet:
    context-path: /

demo:
  message: "This is a message"
  version: 66

demo-props:
  pageSize: 10
  contact:
    pageSize: 5
    successMsg: Your message is submitted successfully.
  branches:
    - NewYork
    - Delhi
    - Paris
    - Singapore
